# config.yaml
program: hypertuning_v5.py
method: grid
name: sweep
metric:
  goal: maximize
  name: eval/f5
parameters:
  lr: 
    values: [1e-5, 6e-6]
  gradient_accumulation_steps:
    values: [16]
  batch_size:
    values: [1]
  stride:
    values: [256, 128]
  max_length:
    values: [1024, 768]
  awp_lr:
    values: [0.1]
  awp_eps:
    values: [1e-4]
  awp_start_epoch:
    values: [1.0]
  neftune_noise_alpha:
    values: [0.05]
