# config.yaml
program: roberta.py
method: grid
name: sweep
metric:
  goal: maximize
  name: eval/f5
parameters:
  lr: 
    values: [1.25e-5, 1.0e-5]
  gradient_accumulation_steps:
    values: [16]
  batch_size:
    values: [1]
  stride:
    values: [128]
  max_length:
    values: [512]
  awp_lr:
    values: [0.1]
  awp_eps:
    values: [1e-4]
  awp_start_epoch:
    values: [1.0, 1.5]
  neftune_noise_alpha:
    values: [0.1]
  training_model_path:
    values: ["FacebookAI/roberta-large"]
